### ISSUE TITLE
Not compatible with other mods that adds new items

### ISSUE THREAD

**Issue by K07H** [ahk1221/SMLHelper#39]
With the current state of development, this mod can conflict with any other mods that adds new items into the game.
This happens because the cache system of SMLHelper can associate already used IDs (from other mods) to new items (from SMLHelper).
This incompatibility problem will not occur for RandyKnapp's mods tho (since his mods items ID have been hardcoded into SMLHelper).

**Comment by PrimeSonic** [comment]
Yes. This issue has existed for a while. It was only first encountered after there were enough mods collectively adding enough new items to actually reach the hard-coded indexes that Randy used in his item IDs.

The only current workaround is to update the internal "ban list" of known hard-coded IDs.  These values are treated as reserved and never issued to new mods adding new items.
While it is an imperfect solution, it is not uncommon to see modders on Nexus release updates to one mod that deal directly improving compatibility with another mod.

Until a more automated solution can be found, if such a solution is even possible, this ban list will need to be kept updated manually. Until such a time, it may not be uncommon to have to release updates to Modding Helper on Nexus that are only for adding new entries to the ban list.

**Comment by K07H** [comment]
If I understand correctly this mod requires its users to wait for an update before they can install other mods that adds new items to the game?

**Comment by K07H** [comment]
So in addition of unexpected behaviour in case of ID conflicts, this issue can lead to very confusing situations when the other mods authors (or users) are not aware that SMLHelper exist.

**Comment by PrimeSonic** [comment]
This isn't unlike the many updates that went into a mod like EasyCraft that released several updates to improve compatibility with other specific mods; Other mods that the user might not even have installed.

And considering that the mods that add new items to the game without using SMLHelper as a framework are countable on one hand, maintaining this list up to date shouldn't be a problem.
And given that the framework provided by SMLHelper greatly reduced the difficulty and barrier to entry for new modders, it's unlikely to see many more mods that add new items without using this framework.

As for having new mod authors being aware of this framework, if they've going through Nexus with open eyes, they will inevitably find Modding Helper.
with over 20 mods using it (and more in the way), not knowing about SMLHelper will be like not knowing about QMods and creating your own mod loader from scratch.

While the concerns are real, I think you may be greatly overestimating how often they will come up.

**Comment by K07H** [comment]
Ok I just hope you'll find a solution for this issue.

**Comment by AlexejheroYTB** [comment]
How many ids do you need @DuckFat ?

**Comment by K07H** [comment]
"I don't see this as too big of an issue, as we can just keep updating the list internally or we could make an external text file that contains all banned ids." Ok so if I understand correctly this mod requires its users to:
- wait for an update of the internal hardcoded ID list of SML Helper.
or
- manually add their ID into SML Helper text file.
in case they want to use a mod that adds new items. (except those from Randy which are already hardcoded in SML Helper)

**Comment by ahk1221** [comment]
Fixed/added workaround
